databases:
  - name: portfolio
    databaseName: portfolio_db
    user: sbalayan

services:
  - type: web
    name: portfolio
    env: ruby
    buildCommand: "./bin/portfolio-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: portfolio_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false